---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: actual-api-secret
  namespace: actual-budget
spec:
  encryptedData:
    ACTUAL_SERVER_PASSWORD: AgCWcrh6TPsOeuYV1yP3APrYTN01FsFZpB+APSCrd9ODnqBOFNm1Oo1Ayj0V5Lk2yqeXSM7X+steH9ch/fxZTa+IKkoqtCN4pT/adRD1tWcS4BWmeq/vX1N8nEvarki+DfhT7ky/wlxmvPQX/LCVluxaM1cq1H0+fZMp0aG+U9RvJz/b1qzgBnVyfJZXuNRaoSdCT5emcNBd4Nis2qwPhNhDjwYiCpKTspleWojORNjkO2QUYDLK245y+AQ7EhE0nrC/OfowJo/uKKR479srnlWrO0WWgGr2jdpJ372FqrKIdJSWMBRpqUsKfWvXKtpnThRozPY0OTDpkjt/U4no3RobxY3Ac+nZCApTjUOTc3Qig0otDB5UU4TrI3aW3RMkSq+LQqZBAi7yzPWMobC8ca/+PlZRftKMuYJNUEFmwklGcj03MJJXq+JA9xTp9CHaLXEa5rpJ8//EQ5isGDEl+kDCK1wnZaMtJCptRiGVAB9U5pu/izx+Cl+VwKBkz6YJrDNjCkcG1xkdv0bGWl9DIKMddLeOg6EQk358YJ+aTdF3Ie5quqM2QQfU13FEQllGLNev4uqJjbOWhcZMKgtyZ4iM+Z/iygJXuO3H2aE1vL21PQMr/v4urQY/skwPYWKDVWBqFOKMNFDG8liqk7OsR4wuyv0OJFZSom0LekWtg4sFY+UNCN5Mf/TY8h3qIvCiWVF0btoayPh1WkKYlvASDX2hFwcb
    API_KEY: AgB0fj3imLzPRm0Ozdx0IsjwQS7UgTkd75ri6W1eCn1o7iK4aiUGK4DAXPrHmKRqAzi2Ta80/EcCGBG9C/bOpMo2xHFIvzCVXe7iDKaC8BktqM7LJEIfRPYGyL9YIy41HIFIcPpdNkYuBTmtdD3/oD9lBUfUTA/7YFj6ADhASbolxWqZDnncaYS41NiSVX6Za5pm/4IJjli4CHobyb/M88YQZkUuhZ+QAe8+09QqdWXnCx0aaCZteq4G+ERbIpn9Xo6fgByHxHa2CmR+DgjdBvuQmh8zrveO1mALELM+0PzEBT06/dQsek5z4uJ3ZPYQ9NgvyE9WAMvOwITHDrJ+oBguQHmscww6hfyOiiR5tXGEr4b1qfksmDG0XbO2VSMWCfiFIYlsBXjBC5uscWnkIN7oQbJ5yXBXzURfd0sEhJhixIoYP8SaCmbJJ+y+Ms1dfW5k4gW3vSjRSet0l6i08EhLCUMLZyb70cRQTuHja+NO+U0fUN051SodFGwTSgA1qaXnFTqczDNYxpfMfhH/mLjXWsh1/XHiXBSX1fk0X327GYOWVmJxhgdlNNE/+JGpBiWY+I+Hr1IxUzPaFX0iQdH5J8rmsKVWDQGnMFbIA+ZnXS/dGuOMJJSQLOfVEqnzRZrArfGzTi1I+ao3ccT4SEgIPVIeQsXB/dNhOxoNKvLcGrQvq3TuAfTO8c6I175LneRlOpJpNW40vDeXC11DoxOPMXMJt4bm1d//QgKVQYzpKbLELfyRIAWUQ39Kh1M2a7ggsveWvM23S87GGH+GUso6
  template:
    metadata:
      name: actual-api-secret
      namespace: actual-budget
    type: Opaque
