---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    tunnelToken: AgB/FUZblUkPZICKcY6TZFmuuZYzU+VTW7kBrsWfsxp9+usc0jQhpsS9+DIqhx30vJ+DGf5u8n0LEhq5bEA0rjebw/Q6n2pUm5Aoj1GF/UHcdarm5KvF6KvuJiSmcJe6Sx0pmLLa2NjlsFLOdJ00XPeFkuNYNzy30VUV1/wMWl0oHrLmRzy+5H5CAs+i1qaW9hjhvCSRTOq6GRC9+WTD0EClywnSGAY13ZOv+m+xvTjTbimbg9UF7v1hRMaR98mc+LiMkQiys8JeJAlzo+uFod8y5qkHGLt8/F44TatKRv+VwcmocxQs/Vg8yCKNqnYIZLN+XOstKtRklOdyUKNtcmeKme34eysc/nxCwENW0RosA0rhM7NmnAmc5u9n7n2ULjjyGSxAg48LvNC21yPdL1FIVLRwlUHi3J0WAdfEzJ6W6RwumGUfLp20f6jxIYEEy/lUqoeyiRu7tiv6BhmiPn098MN8TxjLRXKd64jYm+SooKc1MfLbUYMomzngdF4h3SmINLAV5MGa4TABw6hRnl5UTFXx3fHuqAjUu8aRMH/V5cUTOGUkJTJJcdK6IAJmF/JDQx5OK9yEJpaKtaqu6TpaBm678n8p2Qkz7xLDxyzV/2aSFSECE0c5vPWtZaKndHYW5Jn8SswkrbvcoWpkGQb3AJXQHs969mBBllGS6qBaIU7/vBCPi66SBYRNaKeSh/Q7zKOA2aR+x8lVe9JcSLj4TGQrhbVFCIhUGzyGuyA8oY7tsdEm5KrTz6dBFTOhYz/SNLlirbeSjs9DKtFrERuLGRCVjr5YmvrjChSDhMhDIqkY39Ln3itwrZAq0SfJSe9U0/1Ug2zRaMNxUQpEb2AlBsyPjcvYfU2fcavqTRhS93e80H8La7WvnAD6Mx8pEcpo2dIOyHvjGx0epV31fq14DlQ2J9y33rb+17PBnXfb7vWfsffuoahi
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflared
    type: Opaque
