---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-passwords
  namespace: home-assistant
spec:
  encryptedData:
    passwordfile: AgCxIiRR2gSPxqIQtSk73mUAtrUjQjh1FroFPGOfNeV/3/DgW1cQm5qFE3Vy7pnyarFZm3lkG6LbVO0cHZOnLMmw1st+YIcQy8y+vuW9XlAMJEWZFR/2Az7Uhsh4cM4QvVodnXHlbC3fyRVezKILmX4pBBRVJNpr7I2UXGrsORpaKtPyL+k1zbLIo7t/igMYJgKlQOhVKgoQXXEsFqIXi2BOAZioGL4RB/zccsGTojQezhhgs9nQoG8tmv6k2lfzdzzJ7jm+bIxUDH1nIxYd3Ohn+OF0pNoCNgXTNEbSzArwBGu70YGzwhkERph2TFY+W3SU2jOTLHlN8CVCqK+NOYnZ3zMuqg7no/+Dwpg5CHYfFngmlHSVuaLioWy0SFgGBD6RxRC2agt1+fzhHwDFIxLHK7z2sdmVFxgMuaZCb48LmCOv/jLAkowEiV5ys7L1+ZLEJxKZ92TSxSYW0qQbIDToVwaCrIG7KWEtjbGKj+xKNHnCQMAIA0gwGAkPRQtskMwiWEzHejlb8alv0pf1Qcu62qW4IkKGdwGvgdRTnM/GDp4XUtqiAQ1uLS85YEa7lNVqgqyQAmnVA3h1SQqiweedJTEPQVTVxQmea93nvkyvK9OTijtDmjZeTLIRtN06+evtpnHOlUdBi1kQp73nFg1hl1RvAgAcpRqkdYSFQ4eAhuVF+ndKAm3/ZzYc8IKNy5SriuXHdugzwuZAh+clGkyeplAopTAMFNC6c0cVKGvQRK67e1dM55tMTo3PeVfnKdCLR3h7K0ygyhwRrQSntxbmJiDcsBy2dasK19icHdhDoTcgSN22qakysmlhW4ZpKM00Q0eTtKwRV5kh/MPHff9vfPlteGBooGI5CQ==
  template:
    metadata:
      name: mosquitto-passwords
      namespace: home-assistant
    type: Opaque
