---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-exporter-secret
  namespace: home-assistant
spec:
  encryptedData:
    password: AgBRg7dtmZZ0w+hUUSFKVt7VAtQrwlcVlhjeS9JmeZoWwiHjTQpML2bweigKqwZu64Ecyy1a+XjYFN7588FCFDdBde1eKT4wz4UIQyRyPSnODPtxvb16OaaQybf+wx6oE5dGMnuY/ZTw+LZJcfZJhrb7cqW7W0dxhKKP1MJblECxAfZd51IpUo0NTegnkZmPJm9c8SaouzYxuxqao5DqI4zobn6f9emOxKaUO79fDs3ApmSuygrkNOfbmXiD7G48/Ud3iDKW3BCfdcrTb1hLam+HK/5r1cXk5+lxzdJrNHSqpALz2ssj4zeCc5MYA6xnRARLWu+PvvAbPnkoMm1o/ZodWKUvYxBI80PzaK12BGFf2rrkWRUTMkxAkU5SBzZAWYo0hM7EnyJY62RpWpwvMhzdYFpN4Od35/1GRdTu8dlo2SgNVPQZdJMBbg+GI8tyzR8aABdqHaPhR+aA+C1AV4YOZYPvu1PygOgOBV/vHabtm3wp4ZlKro6jO32BGVOdyOTCLRRKXifIgw3n4j43pOyvxeNcQFqPrOqqfRkJLrqGzO+MC37T3XjsH+6gajYH9esLh2Ts5M4o9SMl4riC7x6b6zzmB4o5dWEji4F+K8DmxJmBH0/8tSfVg+hcgxeByQovpE5b/Js9eTEKCSaJH14lIuPY2cROQs9M6QJHZbpsxp7ELmdIIodMt0kj/dt7cT/Dsx5eMU45AVWWMG+zlfX9LavWM5oR/ecT70JaWYWo9Gz5148VrbFGycPExJNhmR1+4pFbYX/OIGuJtOLArXIzD1sUXdizAQiAEh8CjIoM1H83aCUeecMHDUvd1qlgbHmtM0R2
  template:
    metadata:
      name: mqtt-exporter-secret
      namespace: home-assistant
    type: Opaque
