---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgBVBE0U6EnU6fxBjt35zXXVYg8+BBksaCZ22aQyy1cIRXZTW//g1NzCEEJDlYXnvjIfM1DH1arpzdIM2As2rN+6S2HF5r+s+iPfKXSkLN0T5m2belw8b9OvEARwrU3GxZ3hMZmw9Q6wYoGm4ODyOvtdvISkxUIARwgrLHjA8ka/DJz5034Oz6HtNBGSFYDs6qKYBJx2Oa8gEIn2FWJ3m1ZG9DERi4TfbJupuZE4mfKNkHRiLmxnoqXoHavM09rTNXNAr6evSP+1qOgcsIWVmCgMhGxh/Q6mNJHtmmqWDu+Vc5oqbGQtXu7Wc5QJzjfT8crMnTffvaFrIQLH4XKmdbxchQtS3q6D2T4RWor6D5deuhB+nR50x6wzFjSyf15dMqMpYHgmf8oYqTSie8KECbeH+caWGOIT+vBo5j+eSwB7L+42Bm1Vxmh7YtsL2kzaD9WGwcGCJ49ajRUKiSE9PVbw2sx6gNd3Z41qgqLytoWs9ls9aKJSKnBaCMbWFCEn4jcVx5TGCkjI9hBUBueaNbEec/vqAzePuHEx1RJqL7kkmW1o+MWOXe8fIOkMOBbpWMu5BrjnfS4jNk9V89FjiwXA/TglbE999tTXDtizWNtK4xqK9Ykit3GHyAUzABujIQdQLc+6b30jQPgRteYm9HUD42EjSAYyRZEH4Hieg9TjSrzQbcXNhUVbi8fTSs+pAs6tgXn0jKTMmqzxni3GL7iO/wDTKKDWUBE10wFJF9OgHBLtmRVrcl52UTdjUIpJtv6mYghSh9QKACyvVNyK7qzL
  template:
    metadata:
      name: n8n-encryption-key-secret
      namespace: n8n
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgCyudhVwKf6IELLHLxE95SjyRJZDSt3VjsibgA+ySNVkzrNpyswKAAHXg2tynbYmmPhsVptPV/i67nRNt5+DZ+bZbdrMgW/f0yUSxZzNvm/fJfUaJD2CrDAiolf2OCoEcQLgaNlwW15QnhgBYU3uxdn+jbApBRi+CXNpeSGdjuMAl+PmO1DcdH5VILbV3nwOWh0lZfqSXEoJ6QQMqg7gajbuSV2rJ7y5449/Gj0fsLMsukUFhUSOyQJnVVGiTWVGtoFhhVff0ORBR8BS5EukspNuyWDE9NjQp/GeSJHkwbcJSOqmikkyxXDpiWAxZBJugNifOp8kPVP5GdKPCK09tT7Yj32V3SpvwTXczqUDfeUbSb6wHABXB4rrV4bwt1xuic+13sEND/1hXwJB1WE6XPdGvyZRQ6jXsn+a6Atl+l+K87WSNOQPSNL5gn4HWgMeXeKmCdEIznajjaqq0imKsASezjzEABE/NW4cr6oAu6vajr/UveTmzwtp5UeEQJHnlfYFG3aeZSi7qQWVQwFSPnWCzkG5VjAue9DITDaq21pA3yud942BOIlLrb/dUBaoE3ky45FfW/ud5uIHnFMprDjAI/yHE1qw0lft5SBKpO4jjpE8oqCtHWtvJPrc7fFlpcQgNZKRgxUYglUNJJEH2pBn0fhZ7jkeveDXNNJ4x0Y7kHFMBRQA93pOGh5B9UCZZS0wbE5r4Lcbp79FyE1yRJP1VO+7vfsq14zyhYr0KMTGkTL4SYgd4DWvRarrd2EsC5N+aIkcH1AUFbCmfnkeqQoJyl9hHnjJvJxuCVg
  template:
    metadata:
      name: redis-secret
      namespace: n8n
    type: Opaque
