---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: z2m-passwords
  namespace: home-assistant
spec:
  encryptedData:
    secret.yaml: AgC7jeLxz07gloZxkIq/BNQQUhUgKtm8t1nM5MTEJyt/lUGqXRxn+v2YHyQgWq10mJHA24ZM1Xjc4YvYzEgMR83ej17YczTkozqztX1SfGxvsvG8+nDtl16XJgyZjaRhRUq8urg25Lcs1vWm5sOgpYrAsLxI7zs17lHZkrGmVSSwp04HnpR0zeErCAZiGDuKeqcEs5ROWdB7cWzh7OLukaPTbuna4gf3PHNf1UyKGIKyUTJaXr7u/QRqmYWShoBLdl8v5rTpgjH/bTqGCshyLBvsPOuNUQ7TkLPuwXdqokuYbNhUVXDFKM3x9YcAHkCwqbnfQnnCVr6mfZSA5hqLbepnS3BSc9deOT19SiwEhx9D/ERldvbLgjzq5JLcu//WhPpumSIg4p1f60mG3iOUAdrnhlLy1btJd/d7z/I5SfqvfMw6ErIjT+DLmJmCtzhCDm1WhZ4Rke9HMPytjnxfmaU97MSPUA5PWWnHGuI1Q50AxkML7KladZLfGIAfpcfr1EDBPSXZTj0lXdPrmPSCPTP34NhI94eBoCNYL+9fIpibdJnlykTXmaNdiRLN5n9y3rjFnwv+QvIjYfuYoMGosMoDKVJWQzyamx3CsGsitwp1AvRIcBa6uO1c6+P17c+rNkilFQwlXtcJHbUWW0F4nVindHJaCLZMvZqHi5gVEVQUrpLZyOLaCzvhD0THpfgUcTGhpJOyHTAsCOFp21vr/FD4i/zPv5CBveGsOcjUAmHsRcATvBoUCWbkiXtSke75WvzRTd1m2Fl8ZqUypf+fzgOcG7XBYQXpxgyL0ag3VSwTVIeYKPEv7POLSODoDWtqoOd5jpPHGSQEerzy0e4aupQyUz+m4Fi1HiO5syCj80fN48QmQkjgKkp7fuBwZ2Q=
  template:
    metadata:
      name: z2m-passwords
      namespace: home-assistant
    type: Opaque
