image:
  repository: n8nio/n8n
  tag: 1.115.2

main:
  config:
    db:
      type: postgresdb
      postgresdb:
        host: db-rw
        user: n8n
        #        password: password is read from cnpg db-app secretKeyRef
        pool:
          size: 10
        ssl:
          enabled: true
          reject_Unauthorized: true
          ca_file: "/home/ssl/certs/postgresql/ca.crt"

    external:
      hook:
        files: "/home/node/.n8n/hooks.js"
    n8n:
      editor:
        base:
          url: https://n8n.local.roggeri.com.br
      forward:
        auth:
          header: X-authentik-email
  persistence:
    enabled: true
    type: dynamic
    storageClass: longhorn
    size: 1Gi

  extraEnv:
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: db-app
          key: password
  # Mount the CNPG CA Cert into N8N container
  extraVolumeMounts:
    - name: db-ca-cert
      mountPath: /home/ssl/certs/postgresql
      readOnly: true

  extraVolumes:
    - name: db-ca-cert
      secret:
        secretName: db-ca
        items:
          - key: ca.crt
            path: ca.crt
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd"
  hosts:
    - host: n8n.local.roggeri.com.br
      paths:
        - /

# cnpg DB cluster request
extraManifests:
  - apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: db
    spec:
      instances: 1
      bootstrap:
        initdb:
          database: n8n
          owner: n8n
      postgresql:
        parameters:
          shared_buffers: "64MB"
      resources:
        requests:
          memory: "512Mi"
        limits:
          memory: "512Mi"
      storage:
        size: 1Gi
        storageClass: longhorn
