apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "actual-http-api.fullname" . }}
  labels:
    {{- include "actual-http-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "actual-http-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "actual-http-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ACTUAL_SERVER_URL
              value: {{ .Values.config.actualServerUrl | quote }}
            - name: ACTUAL_DATA_DIR
              value: {{ .Values.persistence.mountPath }}
            {{- if .Values.secrets.passwordSecretName }}
            - name: ACTUAL_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.passwordSecretName }}
                  key: {{ .Values.secrets.passwordSecretKey }}
            {{- end }}
            {{- if .Values.secrets.apiKeySecretName }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.apiKeySecretName }}
                  key: {{ .Values.secrets.apiKeySecretKey }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api-docs/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api-docs/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "actual-http-api.fullname" . }}
      {{- end }}

