repositories:
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  - name: community-charts
    url: https://community-charts.github.io/helm-charts

releases:
  - name: nfs-provisioner
    namespace: kube-system
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values:
      - ./infrastructure/nfs-provisioner/values.yaml

  - name: actual-budget
    namespace: actual-budget
    chart: community-charts/actualbudget
    version: 1.5.2
    values:
      - ./applications/actual-budget/values.yaml
    needs:
      - kube-system/nfs-provisioner
