apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port | int }}
      targetPort: {{ .Values.redis.service.port | int }}
  selector:
    app: redis
