apiVersion: v1
kind: Service
metadata:
  name: {{ include "evolution-api.fullname" . }}
  labels:
    {{- include "evolution-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.evolutionApi.service.type }}
  ports:
    - port: {{ .Values.evolutionApi.service.port | int }}
      targetPort: {{ .Values.evolutionApi.service.port | int }}
      protocol: TCP
      name: http
  selector:
    {{- include "evolution-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
