persistence:
  enabled: true
  storageClass: longhorn
  size: 1Gi

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: home.local.roggeri.com.br
      paths:
        - path: /
          pathType: Prefix

service:
  type: ClusterIP

configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.42.0.0/16
