persistence:
  enabled: true
  storageClass: nfs-client
  size: 5Gi

ingress:
  enabled: true
  hosts:
    - host: home.local.roggeri.com.br
      paths:
        - path: /
          pathType: Prefix

service:
  type: LoadBalancer

configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.42.0.0/16
