version: "3"

networks:
  applications:
    external: true

volumes:
  heimdall_data:

services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    networks:
      - applications
    environment:
      - PUID=1001
      - PGID=1001
      - TZ="America/Sao_Paulo"
    volumes:
      - heimdall_data:/config
    restart: unless-stopped
