volumes:
  homeassistant_config:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  zigbee2mqtt_data:

networks:
  applications:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2024.11.3
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`ha.${DOMAIN}`)
      - traefik.http.routers.homeassistant.entrypoints=websecure
      - traefik.http.services.homeassistant.loadbalancer.server.url=http://host.docker.internal
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
    privileged: true
    network_mode: host
    environment:
      - TZ="America/Sao_Paulo"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mqtt.rule=HostSNI(`mqtt.${DOMAIN}`)
      - traefik.tcp.routers.mqtt.entrypoints=mqtt
      - traefik.tcp.routers.mqtt.tls=true
      - traefik.tcp.routers.mqtt.service=mqtt
      - traefik.tcp.services.mqtt.loadbalancer.server.port=1883
    networks:
      - applications
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    environment:
      - TZ="America/Sao_Paulo"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.41.0
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.${DOMAIN}`)
      - traefik.http.routers.zigbee2mqtt.entrypoints=websecure
    networks:
      - applications
    environment:
      - TZ="America/Sao_Paulo"
    volumes:
      - zigbee2mqtt_data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
