version: "3.8"

volumes:
  immich_pgdata:
  immich_model_cache:
  immich_tsdata:

networks:
  applications:
    external: true
  immich:

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.61.0
    command: ["start-server.sh"]
    environment:
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE_NAME}
      - TYPESENSE_API_KEY=${IMMICH_TYPESENSE_API_KEY}
      - REDIS_HOSTNAME=immich-redis
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
    depends_on:
      - redis
      - database
      - typesense
    networks:
      - immich
    restart: unless-stopped

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:v1.61.0
    command: ["start-microservices.sh"]
    environment:
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE_NAME}
      - TYPESENSE_API_KEY=${IMMICH_TYPESENSE_API_KEY}
      - REDIS_HOSTNAME=immich-redis
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      - immich

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.60.0
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - immich_model_cache:/cache
    restart: unless-stopped
    networks:
      - immich

  immich-web:
    container_name: immich-web
    image: ghcr.io/immich-app/immich-web:v1.60.0
    restart: unless-stopped
    networks:
      - immich

  typesense:
    container_name: immich-typesense
    image: typesense/typesense:0.24.1
    environment:
      - TYPESENSE_API_KEY=${IMMICH_TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - immich_tsdata:/data
    restart: unless-stopped
    networks:
      - immich

  redis:
    container_name: immich-redis
    image: redis:6.2
    restart: unless-stopped
    networks:
      - immich

  database:
    container_name: immich-postgres
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - immich_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich

  immich-proxy:
    container_name: immich-proxy
    image: ghcr.io/immich-app/immich-proxy:v1.60.0
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    depends_on:
      - immich-server
    networks:
      - applications
      - immich
    restart: unless-stopped
