version: "3.8"

volumes:
  immich_pgdata:
  immich_model_cache:

networks:
  applications:
    external: true
  immich:

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.111.0
    environment:
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE_NAME}
      - REDIS_HOSTNAME=immich-redis
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
    devices:
      - /dev/dri:/dev/dri # Enable GPU access for hw encoding
    depends_on:
      - redis
      - database
    networks:
      - immich
      - applications
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.108.0
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - immich_model_cache:/cache
    restart: unless-stopped
    networks:
      - immich
    deploy:
      resources:
        limits:
          cpus: "10"

  redis:
    container_name: immich-redis
    image: redis:7.2
    restart: unless-stopped
    networks:
      - immich

  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - immich_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich
