networks:
  applications:
    external: true

volumes:
  plex_config:
  tautulli_config:
  jellyfin_config:
  jellystat_db:

services:
  plex:
    image: linuxserver/plex:1.40.4
    container_name: plex
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
    networks:
      - applications
    volumes:
      - plex_config:/config
      - /archive/media:/data/
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli:2.14.3
    container_name: tautulli
    restart: unless-stopped
    networks:
      - applications
    volumes:
      - tautulli_config:/config
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo

  jellyfin:
    image: linuxserver/jellyfin:10.9.8
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    networks:
      - applications
    volumes:
      - jellyfin_config:/config
      - /archive/media:/data/
    devices:
      - /dev/dri:/dev/dri

  jellystat-db:
    image: postgres:15.6
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD}
    volumes:
      - jellystat_db:/var/lib/postgresql/data
    networks:
      - applications

  jellystat:
    image: cyfershepard/jellystat:1.1.0
    container_name: jellystat
    restart: unless-stopped
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JELLYSTAT_JWT_SECRET}
      TZ: America/Sao_Paulo
    depends_on:
      - jellystat-db
    networks:
      - applications
