networks:
  applications:
    external: true

volumes:
  plex_config:
  jellyfin_config:

services:
  plex:
    image: linuxserver/plex:1.41.4
    container_name: plex
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
    networks:
      - applications
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - plex_config:/config
      - /archive/media:/data/
      - /data/plex_transcoding:/transcoding
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.routers.plex.rule=Host(`plex.local.${DOMAIN}`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.services.plex.loadbalancer.server.port=32400

  jellyfin:
    image: linuxserver/jellyfin:10.10.6
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    networks:
      - applications
    volumes:
      - jellyfin_config:/config
      - /archive/media:/data/
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.${DOMAIN}`)
      - traefik.http.routers.jellyfin.entrypoints=websecure

