version: "3"

networks:
  applications:
    external: true

volumes:
  transmission_config:
  radarr_config:
  sonarr_config:
  overseerr_config:
  bazarr_config:
  prowlarr_config:


services:
  transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.rule=Host(`transmission.local.${DOMAIN}`)"
      - "traefik.udp.routers.transmission-udp.entrypoints=transmission-udp"
      - "traefik.udp.routers.transmission-udp.service=transmission-udp"
      - "traefik.udp.services.transmission-udp.loadbalancer.server.port=51413"
      
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ="America/Sao_Paulo"
    volumes:
      - /archive/torrents:/data/torrents
      - transmission_config:/config
      - /archive/torrents/downloads:/downloads

  radarr:
    image: linuxserver/radarr:5.8.3
    container_name: radarr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.local.${DOMAIN}`)"
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - radarr_config:/config
      - /archive:/data

  sonarr:
    image: linuxserver/sonarr:4.0.8
    container_name: sonarr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.local.${DOMAIN}`)"
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - sonarr_config:/config
      - /archive:/data

  bazarr:
    image: linuxserver/bazarr:1.4.3
    container_name: bazarr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.local.${DOMAIN}`)"
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - bazarr_config:/config
      - /archive/media:/data/media

  overseerr:
    image: linuxserver/overseerr:1.33.2
    container_name: overseerr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entrypoints=websecure"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.local.${DOMAIN}`)"
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - overseerr_config:/config

  prowlarr:
    image: linuxserver/prowlarr:1.37.0
    container_name: prowlarr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.local.${DOMAIN}`)"
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - prowlarr_config:/config
