version: "3"

networks:
  applications:
    external: true

volumes:
  transmission_config:
  radarr_config:
  sonarr_config:
  overseerr_config:
  bazarr_config:
  prowlarr_config:
  qbittorrent_config:


services:
  transmission:
    image: linuxserver/transmission:4.0.6
    container_name: transmission
    restart: unless-stopped
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ="America/Sao_Paulo"
    volumes:
      - /archive/torrents:/data/torrents
      - transmission_config:/config
      - /archive/torrents/downloads:/downloads

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.6
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ="America/Sao_Paulo"
    volumes:
      - qbittorrent_config:/config
      - /archive/torrents:/data

  radarr:
    image: linuxserver/radarr:5.8.3
    container_name: radarr
    restart: unless-stopped
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - radarr_config:/config
      - /archive:/data

  sonarr:
    image: linuxserver/sonarr:4.0.8
    container_name: sonarr
    restart: unless-stopped
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - sonarr_config:/config
      - /archive:/data

  bazarr:
    image: linuxserver/bazarr:1.4.3
    container_name: bazarr
    restart: unless-stopped
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - bazarr_config:/config
      - /archive/media:/data/media

  overseerr:
    image: linuxserver/overseerr:1.33.2
    container_name: overseerr
    restart: unless-stopped
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - overseerr_config:/config

  prowlarr:
    image: linuxserver/prowlarr:1.21.2
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - applications
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - prowlarr_config:/config
