services:
  broker:
    image: docker.io/library/redis:7.4.0
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
      - paperless_redisdata:/data
    networks:
      - paperless

  db:
    image: docker.io/library/postgres:16.4
    container_name: paperless-postgres
    restart: unless-stopped
    volumes:
      - paperless_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${PAPERLESS_DB_PASSWORD}
    networks:
      - paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.12.1
    container_name: paperless-webserver
    restart: unless-stopped
    depends_on:
      - db
      - broker
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - /archive/data/paperless/export:/usr/src/paperless/export
      - /archive/data/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-postgres
      PAPERLESS_DBPASS: ${PAPERLESS_DB_PASSWORD}
      PAPERLESS_OCR_LANGUAGE: por
      PAPERLESS_OCR_LANGUAGES: por en
      PAPERLESS_TIME_ZONE: America/Sao_Paulo
      PAPERLESS_URL: ${PAPERLESS_URL}
    networks:
      - paperless
      - applications

volumes:
  paperless_data:
  paperless_media:
  paperless_pgdata:
  paperless_redisdata:

networks:
  applications:
    external: true
  paperless:
