volumes:
  pihole_data:
  pihole_dnsmasq:

services:
  pihole:
    image: pihole/pihole:2025.03.0
    container_name: pihole
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local.${DOMAIN}`)"
      - "traefik.http.services.pihole.loadbalancer.server.url=http://host.docker.internal"
      - "traefik.http.services.pihole.loadbalancer.server.port=81"
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - pihole_data:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    environment:
      - DNSMASQ_USER=root
      - TZ=America/Sao_Paulo
      - FTLCONF_dns_interface=enp0s31f6
      - FTLCONF_webserver_port=81
