networks:
  applications:
    external: true

volumes:
  plex_config:
  tautulli_config:

services:
  plex:
    image: linuxserver/plex:1.32.4
    container_name: plex
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
    networks:
      - applications
    volumes:
      - plex_config:/config
      - /archive/media:/data/
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli:2.12.4
    container_name: tautulli
    restart: unless-stopped
    networks:
      - applications
    volumes:
      - tautulli_config:/config
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
