volumes:
  nginx_proxy_manager_data:
  nginx_proxy_manager_letsencrypt:

networks:
  applications:
    external: true

services:
  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:2.10.2
    container_name: nginx_proxy_manager2
    restart: unless-stopped
    networks:
      - applications
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_letsencrypt:/etc/letsencrypt
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 443:443
      - 80:80
      - 8081:81
