volumes:
  nginx_proxy_manager_data:
  nginx_proxy_manager_letsencrypt:

networks:
  applications:
    external: true

services:
  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:2.11.1
    container_name: nginx_proxy_manager2
    restart: unless-stopped
    networks:
      - applications
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_letsencrypt:/etc/letsencrypt
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 443:443
      - 80:80
      - 8081:81
      - 1883:1883/tcp
      - 1883:1883/udp
      - 554:554/tcp
      - 554:554/udp

  cloudflared:
    image: cloudflare/cloudflared:2023.10.0
    container_name: cloudflared
    restart: unless-stopped
    command: "tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN"
    networks:
      - applications
    environment:
      - TZ=America/Sao_Paulo