volumes:
  nginx_proxy_manager_data:
  nginx_proxy_manager_letsencrypt:
  traefik-letsencrypt:

networks:
  applications:
    external: true

services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command: 
      - --providers.docker
      - --log.level=DEBUG
      - --providers.docker.network=applications
      - --providers.docker.exposedByDefault=false
      # TLS Configuration
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${CF_API_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/letsencrypt/acme.json
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
      - --entrypoints.mqtt.address=:1883
      # Redirections
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    networks:
      - applications
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 1883:1883
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt:/etc/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cloudflared:
    image: cloudflare/cloudflared:2024.11.1
    container_name: cloudflared
    restart: unless-stopped
    command: "tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN"
    networks:
      - applications
    environment:
      - TZ=America/Sao_Paulo