version: "3"

volumes:
  wireguard_data:

services:
  heimdall:
    image: linuxserver/wireguard:v1.0.20210914-ls126
    container_name: wireguard
    environment:
      - PUID=1001
      - PGID=1001
      - TZ="America/Sao_Paulo"
    volumes:
      - wireguard_data:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
