version: "2.4"

networks:
  applications:
    external: true

volumes:
  frigate_config:
  frigate_db:

services:
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:2.4.0
    networks:
      - applications
    environment:
      - WYZE_EMAIL=${WYZE_EMAIL}
      - WYZE_PASSWORD=${WYZE_PASSWORD}
      - API_ID=${WYZE_API_ID}
      - API_KEY=${WYZE_API_KEY}
      - ENABLE_AUDIO=True
      - SUBSTREAM=True
      - WB_RTSP_URL=rtsp://${WYZE_RTSP_HOST}/
      - WB_RTMP_URL=rtmp://${WYZE_RTMP_HOST}/
      - WB_HLS_URL=https://${WYZE_HLS_HOST}/
      - WB_WEBRTC_URL=https://${WYZE_WEBRTC_HOST}/
      - FRESH_DATA=True
      - LOG_LEVEL=debug

  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.1
    shm_size: "128mb"
    networks:
      - applications
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /archive/frigate/clips:/media/frigate/clips
      - /archive/frigate/recordings:/media/frigate/recordings
      - frigate_db:/db
      - frigate_config:/config
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
