version: "2.4"

networks:
  applications:
    external: true

services:
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:2.4.0
    networks:
      - applications
    environment:
      - WYZE_EMAIL=${WYZE_EMAIL}
      - WYZE_PASSWORD=${WYZE_PASSWORD}
      - API_ID=${WYZE_API_ID}
      - API_KEY=${WYZE_API_KEY}
      - WB_RTSP_URL=rtsp://${WYZE_RTSP_HOST}/
      - WB_RTMP_URL=rtmp://${WYZE_RTMP_HOST}/
      - WB_HLS_URL=https://${WYZE_HLS_HOST}/
      - WB_WEBRTC_URL=https://${WYZE_WEBRTC_HOST}/
