persistence:
  enabled: true
  storageClass: longhorn
  size: 200Mi

service:
  type: ClusterIP
  port: 5006

ingress:
  enabled: true
  hosts:
    - host: budget.local.roggeri.com.br
      paths:
        - path: /
          pathType: Prefix

image:
  repository: andreroggeri/actual
  tag: payee-name-fix
