apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mixuruca.fullname" . }}
  labels:
    {{- include "mixuruca.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.dashboardHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mixuruca.fullname" . }}
                port:
                  name: http
    - host: {{ .Values.ingress.novncHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mixuruca.fullname" . }}
                port:
                  name: novnc
