apiVersion: v1
kind: Service
metadata:
  name: {{ include "mixuruca.fullname" . }}
  labels:
    {{- include "mixuruca.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mixuruca.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: novnc
      port: {{ .Values.service.novncPort }}
      targetPort: novnc
