vpn_clients_static:
  hosts:
    nas:
      ansible_host: 192.168.15.4
      wg_private_ip: 10.8.0.2
      wg_public_key: "{{ wg_nas_public_key }}"
      wg_private_key: "{{ wg_nas_private_key }}"
    office-pi:
      ansible_host: 192.168.15.137
      wg_private_ip: 10.8.0.7
      wg_public_key: "{{ wg_raspberry_pi_office_public_key }}"
      wg_private_key: "{{ wg_raspberry_pi_office_private_key }}"

# TODO: Read from terraform
vpn_clients_dynamic:
  hosts:
    k3s-node-01:
      ansible_host: 193.123.106.26
      wg_private_ip: 10.8.0.13
    agendaodonto:
      ansible_host: 204.216.135.129
      wg_private_ip: 10.8.0.10
    gateway:
      ansible_host: 204.216.132.96
      wg_private_ip: 10.8.0.11

vpn_server:
  hosts:
    vpn-server:
      ansible_host: 204.216.165.63

k3s_cluster:
  children:
    server:
      hosts:
        10.8.0.2:
        10.8.0.13:
    agents:
      hosts:
        # TODO: Add agents
        #
