apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
  ports:
    - name: registry
      port: {{ .Values.service.port }}
      targetPort: registry
