{{- if .Values.serverTransport.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ include "trilium.fullname" . }}-transport
  labels:
    {{- include "trilium.labels" . | nindent 4 }}
spec:
  forwardingTimeouts:
    dialTimeout: {{ .Values.serverTransport.forwardingTimeouts.dialTimeout }}
    responseHeaderTimeout: {{ .Values.serverTransport.forwardingTimeouts.responseHeaderTimeout }}
    idleConnTimeout: {{ .Values.serverTransport.forwardingTimeouts.idleConnTimeout }}
{{- end }}
